"""empty message

Revision ID: 6e41ad356161
Revises: fbe42fbeed58
Create Date: 2021-06-10 13:04:04.308981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e41ad356161'
down_revision = 'fbe42fbeed58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chats', ['name'])
    op.add_column('users', sa.Column('location', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_constraint(None, 'chats', type_='unique')
    # ### end Alembic commands ###
